### PR TITLE
build ignore vignettes + prefix sf calls

### PR DESCRIPTION
**Pull request by olivroy**

### CODE REVIEW

**Comment by mtennekes** [comment]
Thanks! Is it possible (easy) to show the dev site on https://r-tmap.github.io/tmap/ ? And optionally the old site at for instance https://r-tmap.github.io/tmap/release?

**Comment by olivroy** [comment]
I am not aware of a simple way to do this. Deleting `mode: auto` from `_pkgdown.yml` will show the dev site only... I think this is fine now! 

I have been using tmap's release candidate for ~ 1 month now, and I got everything working perfectly! Since we are quite close to release, I don't see a need for keeping v3 site around.

(It will disappear anyway when v4 is released) 

There is an enhancement request on pkgdown's side: https://github.com/r-lib/pkgdown/issues/1373

**Comment by mtennekes** [comment]
Totally agree!

Now is the time to write those vignettes, and finish the documentation (especially about `tm_options`, which those many options)

**Comment by olivroy** [comment]
Agreed! 

there are also a couple of issues left. You may want to scan through again.

I added the revdep check workflow. Hopefully, we'll get insights about reverse dependencies. I will open an issue with the problems once the run finishes.

**Pull request merged**
